import { randomUUID } from 'crypto';
import { AppDataSource } from '../config/database';
const ACTIVE=new Set(['open','in_progress','waiting_customer']);
function text(value:unknown){const v=String(value||'').trim();if(v.length<2)throw new Error('Message must contain at least 2 characters');if(v.length>5000)throw new Error('Message cannot exceed 5000 characters');return v;}
export class VendorSupportService {
  async list(vendorId:string){const items=await AppDataSource.query("SELECT * FROM support_tickets WHERE requester_type='vendor' AND requester_id=? ORDER BY updated_at DESC",[vendorId]);return{items,total:items.length};}
  async get(vendorId:string,id:string){const rows:any[]=await AppDataSource.query("SELECT * FROM support_tickets WHERE id=? AND requester_type='vendor' AND requester_id=?",[id,vendorId]);if(!rows[0])throw new Error('Support ticket not found');const messages=await AppDataSource.query('SELECT * FROM support_ticket_messages WHERE ticket_id=? ORDER BY created_at ASC,id ASC',[id]);return{...rows[0],messages};}
  async create(vendorId:string,input:any){const subject=String(input.subject||'').trim();if(subject.length<4||subject.length>180)throw new Error('Subject must contain 4 to 180 characters');const body=text(input.message??input.description);const id=randomUUID();await AppDataSource.transaction(async m=>{await m.query("INSERT INTO support_tickets(id,requester_id,requester_type,subject,category,priority,status,metadata) VALUES (?,?,?,?,?,?, 'open',?)",[id,vendorId,'vendor',subject,String(input.category||'general').slice(0,48),['low','medium','high','urgent'].includes(input.priority)?input.priority:'medium',JSON.stringify(input.metadata||{})]);await m.query('INSERT INTO support_ticket_messages(id,ticket_id,sender_id,sender_type,message,attachments) VALUES (?,?,?,?,?,?)',[randomUUID(),id,vendorId,'vendor',body,JSON.stringify([])]);});return this.get(vendorId,id);}
  async message(vendorId:string,id:string,input:any){const body=text(input.message);await AppDataSource.transaction(async m=>{const rows:any[]=await m.query("SELECT * FROM support_tickets WHERE id=? AND requester_type='vendor' AND requester_id=? FOR UPDATE",[id,vendorId]);if(!rows[0])throw new Error('Support ticket not found');if(!ACTIVE.has(rows[0].status))throw new Error('Resolved or closed tickets cannot receive messages');await m.query('INSERT INTO support_ticket_messages(id,ticket_id,sender_id,sender_type,message,attachments) VALUES (?,?,?,?,?,?)',[randomUUID(),id,vendorId,'vendor',body,JSON.stringify([])]);await m.query("UPDATE support_tickets SET status=CASE WHEN status='waiting_customer' THEN 'in_progress' ELSE status END,updated_at=CURRENT_TIMESTAMP(6) WHERE id=?",[id]);});return this.get(vendorId,id);}
  async close(vendorId:string,id:string){await this.get(vendorId,id);await AppDataSource.query("UPDATE support_tickets SET status='closed',resolved_at=COALESCE(resolved_at,CURRENT_TIMESTAMP(6)) WHERE id=?",[id]);return this.get(vendorId,id);}
}
