import { randomUUID } from 'crypto';
import { AppDataSource } from '../config/database';
import { sendSocialPush } from './notificationClient.service';
const TERMINAL = new Set(['rejected', 'ended', 'missed']);
export class CallService {
  private async conversation(userId:string,id:string){const rows:any[]=await AppDataSource.query('SELECT * FROM social_conversations WHERE id=? AND (participant_one_id=? OR participant_two_id=?)',[id,userId,userId]);if(!rows[0])throw Object.assign(new Error('Conversation not found'),{statusCode:404});return rows[0];}
  private async expire(){await AppDataSource.query("UPDATE social_calls SET status='missed',ended_at=CURRENT_TIMESTAMP(6) WHERE status='ringing' AND expires_at<CURRENT_TIMESTAMP(6)");}
  async start(userId:string,conversationId:string,input:any){const conv=await this.conversation(userId,conversationId);const callee=conv.participant_one_id===userId?conv.participant_two_id:conv.participant_one_id;const type=String(input.type||'audio');if(!['audio','video'].includes(type))throw new Error('Call type must be audio or video');const key=String(input.idempotencyKey||randomUUID()).slice(0,80);const existing:any[]=await AppDataSource.query('SELECT * FROM social_calls WHERE caller_id=? AND idempotency_key=?',[userId,key]);if(existing[0])return existing[0];const active:any[]=await AppDataSource.query("SELECT id FROM social_calls WHERE conversation_id=? AND status IN ('ringing','accepted') LIMIT 1",[conversationId]);if(active[0])throw Object.assign(new Error('A call is already active in this conversation'),{statusCode:409});const id=randomUUID();await AppDataSource.query("INSERT INTO social_calls(id,conversation_id,caller_id,callee_id,call_type,status,idempotency_key,offer_sdp,expires_at) VALUES (?,?,?,?,?,'ringing',?,?,DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL 60 SECOND))",[id,conversationId,userId,callee,type,key,input.offerSdp||null]);void sendSocialPush(callee,`Incoming ${type} call`,'Tap to answer the call',`/socio?call=${id}`,{type:'social_call',callId:id,conversationId,status:'ringing'});return this.get(userId,id);}
  async get(userId:string,id:string){await this.expire();const rows:any[]=await AppDataSource.query('SELECT * FROM social_calls WHERE id=? AND (caller_id=? OR callee_id=?)',[id,userId,userId]);if(!rows[0])throw Object.assign(new Error('Call not found'),{statusCode:404});return rows[0];}
  async list(userId:string){await this.expire();return AppDataSource.query('SELECT * FROM social_calls WHERE caller_id=? OR callee_id=? ORDER BY created_at DESC LIMIT 100',[userId,userId]);}
  async accept(userId:string,id:string,answerSdp?:string){const row:any=await this.get(userId,id);if(row.callee_id!==userId)throw Object.assign(new Error('Only the callee can accept this call'),{statusCode:403});if(row.status==='accepted')return row;if(row.status!=='ringing')throw new Error('Call is no longer ringing');await AppDataSource.query("UPDATE social_calls SET status='accepted',answer_sdp=?,accepted_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='ringing'",[answerSdp||null,id]);void sendSocialPush(row.caller_id,'Call answered','Your call was answered',`/socio?call=${id}`,{type:'social_call',callId:id,status:'accepted'});return this.get(userId,id);}
  async reject(userId:string,id:string){const row:any=await this.get(userId,id);if(row.callee_id!==userId)throw Object.assign(new Error('Only the callee can reject this call'),{statusCode:403});if(row.status==='rejected')return row;if(row.status!=='ringing')throw new Error('Call is no longer ringing');await AppDataSource.query("UPDATE social_calls SET status='rejected',ended_at=CURRENT_TIMESTAMP(6) WHERE id=?",[id]);void sendSocialPush(row.caller_id,'Call declined','The call was declined',`/socio?call=${id}`,{type:'social_call',callId:id,status:'rejected'});return this.get(userId,id);}
  async end(userId:string,id:string){const row:any=await this.get(userId,id);if(TERMINAL.has(row.status))return row;await AppDataSource.query("UPDATE social_calls SET status='ended',ended_at=CURRENT_TIMESTAMP(6) WHERE id=?",[id]);const other=row.caller_id===userId?row.callee_id:row.caller_id;void sendSocialPush(other,'Call ended','The call has ended',`/socio?call=${id}`,{type:'social_call',callId:id,status:'ended'});return this.get(userId,id);}
  async signal(userId:string,id:string,input:any){const row:any=await this.get(userId,id);if(!['ringing','accepted'].includes(row.status))throw new Error('Call is not active');const type=String(input.type||'candidate');if(!['candidate','offer','answer','renegotiate'].includes(type))throw new Error('Invalid signal type');const signalId=randomUUID();await AppDataSource.query('INSERT INTO social_call_signals(id,call_id,sender_id,signal_type,payload_json) VALUES (?,?,?,?,?)',[signalId,id,userId,type,JSON.stringify(input.payload||{})]);return{id:signalId,callId:id,type};}
  async signals(userId:string,id:string,since=0){await this.get(userId,id);return AppDataSource.query('SELECT sequence_no,id,sender_id,signal_type,payload_json,created_at FROM social_call_signals WHERE call_id=? AND sequence_no>? AND sender_id<>? ORDER BY sequence_no ASC LIMIT 200',[id,Math.max(since,0),userId]);}
}
