import { Request, Response, Router } from 'express';
import { sendBadRequest, sendCreated, sendForbidden, sendNotFound, sendSuccess, sendUnauthorized } from '../middleware/responseEnvelope';
import { FoodService } from '../service/food.service';
import { FoodPhase2Service } from '../service/foodPhase2.service';
import { resolveVendorIdFromAuth } from '../service/vendorContext.service';
const actor = (req: Request): any => (req as any).auth;
const subject = (req: Request) => { const id = actor(req)?.customer_id || actor(req)?.sub; return id ? String(id) : null; };
const hasRole = (req: Request, role: string) => (actor(req)?.realm_access?.roles || []).some((v: unknown) => String(v).toUpperCase() === role);
const fail = (res: Response, error: unknown) => sendBadRequest(res, error instanceof Error ? error.message : 'Food request failed');

export function createFoodPhase2Routes(): Router {
  const router = Router(); const service = new FoodService(); const phase2 = new FoodPhase2Service();
  router.post('/coupons/validate', async (req, res) => { const id=subject(req); if(!id)return sendUnauthorized(res); try{sendSuccess(res,await phase2.validateCoupon(String(req.body?.code||''),id,String(req.body?.restaurantId||''),Number(req.body?.subtotal||0)));}catch(e){fail(res,e);} });
  router.post('/orders/:orderId/payment', async (req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{sendCreated(res,await phase2.createPayment(id,req.params.orderId,String(req.body?.provider||'razorpay'),req.headers.authorization));}catch(e){fail(res,e);}});
  router.get('/orders/:orderId/tracking', async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{sendSuccess(res,await phase2.trackOrder(id,req.params.orderId));}catch(e){fail(res,e);}});
  router.get('/orders/:orderId/invoice', async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{sendSuccess(res,await phase2.getInvoice(id,req.params.orderId));}catch(e){fail(res,e);}});
  router.get('/orders/:orderId/invoice.pdf', async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{const pdf=await phase2.getInvoicePdf(id,req.params.orderId);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename=food-invoice-.pdf`);res.send(pdf);}catch(e){fail(res,e);}});
  router.post('/menu/items/:itemId/back-in-stock',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{sendCreated(res,await phase2.subscribeBackInStock(id,req.params.itemId));}catch(e){fail(res,e);}});
  router.get('/notifications',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);try{sendSuccess(res,await phase2.listNotifications(id));}catch(e){fail(res,e);}});

  router.get('/rider/profile',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.getRiderByUser(id));}catch(e){fail(res,e);}});
  router.put('/rider/profile',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.saveRiderProfile(id,req.body||{}));}catch(e){fail(res,e);}});
  router.patch('/rider/online',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.setRiderOnline(id,Boolean(req.body?.online)));}catch(e){fail(res,e);}});
  router.post('/rider/location',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.updateRiderLocation(id,Number(req.body?.latitude),Number(req.body?.longitude),req.body?.orderId));}catch(e){fail(res,e);}});
  router.get('/rider/assignments',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.listRiderAssignments(id));}catch(e){fail(res,e);}});
  router.post('/rider/assignments/:assignmentId/respond',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.respondToAssignment(id,req.params.assignmentId,Boolean(req.body?.accept),req.body?.reason));}catch(e){fail(res,e);}});
  router.post('/rider/assignments/:assignmentId/pickup',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.pickup(id,req.params.assignmentId));}catch(e){fail(res,e);}});
  router.post('/rider/assignments/:assignmentId/deliver',async(req,res)=>{const id=subject(req);if(!id)return sendUnauthorized(res);if(!hasRole(req,'RIDER')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Rider access required');try{sendSuccess(res,await phase2.deliver(id,req.params.assignmentId,String(req.body?.otp||'')));}catch(e){fail(res,e);}});

  router.post('/vendor/orders/:orderId/assign-rider',async(req,res)=>{if(!hasRole(req,'VENDOR')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Vendor access required');try{const vendorId=await resolveVendorIdFromAuth(actor(req));if(!vendorId)return sendForbidden(res,'Vendor profile not found');const order=await service.getVendorOrder(vendorId,req.params.orderId);if(!order)return sendNotFound(res,'Food order not found');sendSuccess(res,await phase2.autoAssign(order.id));}catch(e){fail(res,e);}});
  router.post('/vendor/menu/items/:itemId/notify-stock',async(req,res)=>{if(!hasRole(req,'VENDOR')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Vendor access required');try{sendSuccess(res,await phase2.notifyBackInStock(req.params.itemId));}catch(e){fail(res,e);}});

  router.get('/admin/orders',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listAdminOrders(req.query.status?String(req.query.status):undefined));}catch(e){fail(res,e);}});
  router.get('/admin/riders',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listAdminRiders());}catch(e){fail(res,e);}});
  router.patch('/admin/riders/:riderId/approval',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.approveRider(req.params.riderId,Boolean(req.body?.approved)));}catch(e){fail(res,e);}});
  router.post('/admin/coupons',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendCreated(res,await phase2.saveCoupon(req.body||{}));}catch(e){fail(res,e);}});
  router.put('/admin/coupons/:couponId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.saveCoupon({...req.body,id:req.params.couponId}));}catch(e){fail(res,e);}});
  router.post('/admin/orders/:orderId/refunds',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendCreated(res,await phase2.initiateRefund(req.params.orderId,subject(req)||'admin',req.body||{}));}catch(e){fail(res,e);}});
  router.patch('/admin/refunds/:refundId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await (req.body?.success===false?phase2.completeRefund(req.params.refundId,false):phase2.executeProviderRefund(req.params.refundId,req.headers.authorization)));}catch(e){fail(res,e);}});
  router.get('/vendor/combos',async(req,res)=>{if(!hasRole(req,'VENDOR')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Vendor access required');try{const vendorId=await resolveVendorIdFromAuth(actor(req));if(!vendorId)return sendForbidden(res,'Vendor profile not found');const restaurant=await service.getVendorRestaurant(vendorId);if(!restaurant)return sendNotFound(res,'Restaurant not found');sendSuccess(res,await phase2.listCombos(restaurant.id,true));}catch(e){fail(res,e);}});
  router.post('/vendor/combos',async(req,res)=>{if(!hasRole(req,'VENDOR')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Vendor access required');try{const vendorId=await resolveVendorIdFromAuth(actor(req));if(!vendorId)return sendForbidden(res,'Vendor profile not found');const restaurant=await service.getVendorRestaurant(vendorId);if(!restaurant)return sendNotFound(res,'Restaurant not found');sendCreated(res,await phase2.saveCombo(restaurant.id,req.body||{}));}catch(e){fail(res,e);}});
  router.put('/vendor/combos/:comboId',async(req,res)=>{if(!hasRole(req,'VENDOR')&&!hasRole(req,'ADMIN'))return sendForbidden(res,'Vendor access required');try{const vendorId=await resolveVendorIdFromAuth(actor(req));if(!vendorId)return sendForbidden(res,'Vendor profile not found');const restaurant=await service.getVendorRestaurant(vendorId);if(!restaurant)return sendNotFound(res,'Restaurant not found');sendSuccess(res,await phase2.saveCombo(restaurant.id,{...req.body,id:req.params.comboId}));}catch(e){fail(res,e);}});
  router.get('/admin/restaurants',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listAdminRestaurants());}catch(e){fail(res,e);}});
  router.patch('/admin/restaurants/:restaurantId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.setAdminRestaurantState(req.params.restaurantId,req.body||{}));}catch(e){fail(res,e);}});
  router.get('/admin/coupons',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listAdminCoupons());}catch(e){fail(res,e);}});
  router.get('/admin/refunds',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listAdminRefunds(req.query.status?String(req.query.status):undefined));}catch(e){fail(res,e);}});
  router.get('/admin/rider-settlements',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.listRiderSettlements(req.query.status?String(req.query.status):undefined));}catch(e){fail(res,e);}});
  router.post('/admin/rider-settlements/:settlementId/pay',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.completeRiderSettlement(req.params.settlementId,String(req.body?.transactionRef||'')));}catch(e){fail(res,e);}});  router.post('/admin/restaurants',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{const vendorId=String(req.body?.vendorId||'').trim();if(!vendorId)throw new Error('vendorId is required');sendCreated(res,await service.saveVendorRestaurant(vendorId,{...req.body,name:req.body?.name||req.body?.title,minOrderAmount:req.body?.minOrderAmount??req.body?.minOrder,vegOnly:req.body?.vegOnly??req.body?.isPureVeg}));}catch(e){fail(res,e);}});
  router.post('/admin/riders',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{const userId=String(req.body?.userId||'').trim();if(!userId)throw new Error('userId is required');sendCreated(res,await phase2.saveRiderProfile(userId,{...req.body,phone:req.body?.phone||req.body?.mobile,vehicleNumber:req.body?.vehicleNumber||req.body?.vehicleNo}));}catch(e){fail(res,e);}});
  router.patch('/admin/riders/:riderId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.updateAdminRider(req.params.riderId,req.body||{}));}catch(e){fail(res,e);}});
  router.delete('/admin/coupons/:couponId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.deactivateCoupon(req.params.couponId));}catch(e){fail(res,e);}});
  router.patch('/admin/orders/:orderId',async(req,res)=>{if(!hasRole(req,'ADMIN'))return sendForbidden(res,'Admin access required');try{sendSuccess(res,await phase2.adminChangeOrderStatus(req.params.orderId,String(req.body?.status||''),subject(req)||'admin',req.body?.note));}catch(e){fail(res,e);}});  return router;
}
